//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaVentasEntities : DbContext
    {
        public SistemaVentasEntities()
            : base("name=SistemaVentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCategoria> tbCategoria { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbCompraDetalles> tbCompraDetalles { get; set; }
        public virtual DbSet<tbCompras> tbCompras { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbMetodoPago> tbMetodoPago { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbProductos> tbProductos { get; set; }
        public virtual DbSet<tbProveedores> tbProveedores { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbventa> tbventa { get; set; }
        public virtual DbSet<tbventaDetalles> tbventaDetalles { get; set; }
    
        public virtual int UDP_BorrarCargo(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_BorrarCargo", idEdicionParameter);
        }
    
        public virtual int UDP_BorrarCaTegorias(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_BorrarCaTegorias", idEdicionParameter);
        }
    
        public virtual int UDP_BorrarUsuario(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_BorrarUsuario", idEdicionParameter);
        }
    
        public virtual int UDP_Borrarventa(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Borrarventa", idEdicionParameter);
        }
    
        public virtual ObjectResult<UDP_BuscarProveedores_Result> UDP_BuscarProveedores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_BuscarProveedores_Result>("UDP_BuscarProveedores");
        }
    
        public virtual int UDP_CambiarContrasenia(string usuario, string contrasenia)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseniaParameter = contrasenia != null ?
                new ObjectParameter("Contrasenia", contrasenia) :
                new ObjectParameter("Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_CambiarContrasenia", usuarioParameter, contraseniaParameter);
        }
    
        public virtual ObjectResult<UDP_ComprasIndex_Result> UDP_ComprasIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_ComprasIndex_Result>("UDP_ComprasIndex");
        }
    
        public virtual int UDP_ComprasInsert(Nullable<int> proveedorId, Nullable<int> compraUsuarioCreacion)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("proveedorId", proveedorId) :
                new ObjectParameter("proveedorId", typeof(int));
    
            var compraUsuarioCreacionParameter = compraUsuarioCreacion.HasValue ?
                new ObjectParameter("compraUsuarioCreacion", compraUsuarioCreacion) :
                new ObjectParameter("compraUsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_ComprasInsert", proveedorIdParameter, compraUsuarioCreacionParameter);
        }
    
        public virtual int UDP_EditarCargo(Nullable<int> idEdicion, string cargo, Nullable<int> usuarioModificacion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarCargo", idEdicionParameter, cargoParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EditarClientes(Nullable<int> id, string nombre, string apellido, string municipio, string direccion, string telefono, string email, Nullable<int> usuarioModificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarClientes", idParameter, nombreParameter, apellidoParameter, municipioParameter, direccionParameter, telefonoParameter, emailParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EditarEmpleados(Nullable<int> id, string nombre, string apellido, string sexo, string municipio, string direccionExacta, string estadoCivil, string telefono, string correo, string fechaNacimiento, string fechaContaratacion, string cargo, Nullable<int> usuarioModificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var estadoCivilParameter = estadoCivil != null ?
                new ObjectParameter("EstadoCivil", estadoCivil) :
                new ObjectParameter("EstadoCivil", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var fechaContaratacionParameter = fechaContaratacion != null ?
                new ObjectParameter("FechaContaratacion", fechaContaratacion) :
                new ObjectParameter("FechaContaratacion", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarEmpleados", idParameter, nombreParameter, apellidoParameter, sexoParameter, municipioParameter, direccionExactaParameter, estadoCivilParameter, telefonoParameter, correoParameter, fechaNacimientoParameter, fechaContaratacionParameter, cargoParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EditarProducto(Nullable<int> id, string nombre, Nullable<decimal> precio, Nullable<int> categoria, Nullable<int> proveedor, Nullable<int> stock, Nullable<int> usuarioModificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(int));
    
            var proveedorParameter = proveedor.HasValue ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarProducto", idParameter, nombreParameter, precioParameter, categoriaParameter, proveedorParameter, stockParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EditarProveedores(Nullable<int> id, string nombre, string municipio, string direccion, string telefono, string email, Nullable<int> usuarioModificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarProveedores", idParameter, nombreParameter, municipioParameter, direccionParameter, telefonoParameter, emailParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EliminarClientes(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarClientes", idParameter);
        }
    
        public virtual int UDP_EliminarEmpleados(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarEmpleados", idParameter);
        }
    
        public virtual int UDP_EliminarProducto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarProducto", idParameter);
        }
    
        public virtual int UDP_EliminarProveedores(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarProveedores", idParameter);
        }
    
        public virtual ObjectResult<UDP_IndexCargos_Result> UDP_IndexCargos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexCargos_Result>("UDP_IndexCargos");
        }
    
        public virtual ObjectResult<UDP_IndexCategorias_Result> UDP_IndexCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexCategorias_Result>("UDP_IndexCategorias");
        }
    
        public virtual ObjectResult<UDP_IndexEmpleados_Result> UDP_IndexEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexEmpleados_Result>("UDP_IndexEmpleados");
        }
    
        public virtual ObjectResult<UDP_IndexUsuario_Result> UDP_IndexUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexUsuario_Result>("UDP_IndexUsuario");
        }
    
        public virtual ObjectResult<UDP_IndexventaDetalles_Result> UDP_IndexventaDetalles(Nullable<int> ventaId)
        {
            var ventaIdParameter = ventaId.HasValue ?
                new ObjectParameter("ventaId", ventaId) :
                new ObjectParameter("ventaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexventaDetalles_Result>("UDP_IndexventaDetalles", ventaIdParameter);
        }
    
        public virtual ObjectResult<UDP_Indexventas_Result> UDP_Indexventas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Indexventas_Result>("UDP_Indexventas");
        }
    
        public virtual int UDP_InsertarCargos(string cargo, Nullable<int> usuarioCreacion)
        {
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarCargos", cargoParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_InsertarCategorias(string categoria, Nullable<int> usuarioCreacion)
        {
            var categoriaParameter = categoria != null ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarCategorias", categoriaParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_InsertarClientes(string nombre, string apellido, string municipio, string direccion, string telefono, string email, Nullable<int> usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarClientes", nombreParameter, apellidoParameter, municipioParameter, direccionParameter, telefonoParameter, emailParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_InsertarEmpleados(string nombre, string apellido, string sexo, string municipio, string direccionExacta, string estadoCivil, string telefono, string correo, string fechaNacimiento, string fechaContaratacion, string cargo, Nullable<int> usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var estadoCivilParameter = estadoCivil != null ?
                new ObjectParameter("EstadoCivil", estadoCivil) :
                new ObjectParameter("EstadoCivil", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var fechaContaratacionParameter = fechaContaratacion != null ?
                new ObjectParameter("FechaContaratacion", fechaContaratacion) :
                new ObjectParameter("FechaContaratacion", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarEmpleados", nombreParameter, apellidoParameter, sexoParameter, municipioParameter, direccionExactaParameter, estadoCivilParameter, telefonoParameter, correoParameter, fechaNacimientoParameter, fechaContaratacionParameter, cargoParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_InsertarProductos(string nombre, Nullable<decimal> precio, Nullable<int> categoria, Nullable<int> proveedor, Nullable<int> stock, Nullable<int> usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(int));
    
            var proveedorParameter = proveedor.HasValue ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarProductos", nombreParameter, precioParameter, categoriaParameter, proveedorParameter, stockParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_InsertarProveedores(string nombre, string municipio, string direccion, string telefono, string email, Nullable<int> usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarProveedores", nombreParameter, municipioParameter, direccionParameter, telefonoParameter, emailParameter, usuarioCreacionParameter);
        }
    
        public virtual int UDP_Insertarventa(string clienteId, string metodoPago, string empleadoId, string usuarioCreacion)
        {
            var clienteIdParameter = clienteId != null ?
                new ObjectParameter("ClienteId", clienteId) :
                new ObjectParameter("ClienteId", typeof(string));
    
            var metodoPagoParameter = metodoPago != null ?
                new ObjectParameter("MetodoPago", metodoPago) :
                new ObjectParameter("MetodoPago", typeof(string));
    
            var empleadoIdParameter = empleadoId != null ?
                new ObjectParameter("EmpleadoId", empleadoId) :
                new ObjectParameter("EmpleadoId", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_Insertarventa", clienteIdParameter, metodoPagoParameter, empleadoIdParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_LlenarCliente_Result> UDP_LlenarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_LlenarCliente_Result>("UDP_LlenarCliente");
        }
    
        public virtual ObjectResult<UDP_LlenarProductos_Result> UDP_LlenarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_LlenarProductos_Result>("UDP_LlenarProductos");
        }
    
        public virtual ObjectResult<UDP_Login_Result> UDP_Login(string usuario, string contrasenia)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseniaParameter = contrasenia != null ?
                new ObjectParameter("Contrasenia", contrasenia) :
                new ObjectParameter("Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Login_Result>("UDP_Login", usuarioParameter, contraseniaParameter);
        }
    
        public virtual ObjectResult<UDP_SelectIdVentaMax_Result> UDP_SelectIdVentaMax()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_SelectIdVentaMax_Result>("UDP_SelectIdVentaMax");
        }
    
        public virtual ObjectResult<string> UDP_SelectMunicipiosByDepartamentoId(string departamentoId)
        {
            var departamentoIdParameter = departamentoId != null ?
                new ObjectParameter("departamentoId", departamentoId) :
                new ObjectParameter("departamentoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_SelectMunicipiosByDepartamentoId", departamentoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_SelectIdVentaMax1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_SelectIdVentaMax1");
        }
    
        public virtual ObjectResult<UDP_SelectProductoByProveedor_Result> UDP_SelectProductoByProveedor(Nullable<int> proveedorId)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("proveedorId", proveedorId) :
                new ObjectParameter("proveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_SelectProductoByProveedor_Result>("UDP_SelectProductoByProveedor", proveedorIdParameter);
        }
    
        public virtual ObjectResult<UDP_SelectProductos_Result> UDP_SelectProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_SelectProductos_Result>("UDP_SelectProductos");
        }
    
        public virtual ObjectResult<string> UDP_SelectMunicipiosByDepartamentoId1(string departamentoId)
        {
            var departamentoIdParameter = departamentoId != null ?
                new ObjectParameter("departamentoId", departamentoId) :
                new ObjectParameter("departamentoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_SelectMunicipiosByDepartamentoId1", departamentoIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_SelectIdVentaMax2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_SelectIdVentaMax2");
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_SelectIdVentaMax3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_SelectIdVentaMax3");
        }
    
        public virtual int UDP_EliminarVenta(Nullable<int> ventaId)
        {
            var ventaIdParameter = ventaId.HasValue ?
                new ObjectParameter("ventaId", ventaId) :
                new ObjectParameter("ventaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarVenta", ventaIdParameter);
        }
    
        public virtual int UDP_InsertarventaDetalles(string productoId, string cantidad, string usuarioCreacion)
        {
            var productoIdParameter = productoId != null ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(string));
    
            var cantidadParameter = cantidad != null ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarventaDetalles", productoIdParameter, cantidadParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_CargarMunicipios_Result> UDP_CargarMunicipios(string departamentoId)
        {
            var departamentoIdParameter = departamentoId != null ?
                new ObjectParameter("departamentoId", departamentoId) :
                new ObjectParameter("departamentoId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarMunicipios_Result>("UDP_CargarMunicipios", departamentoIdParameter);
        }
    
        public virtual ObjectResult<UDP_DetalleEnTabla_Result6> UDP_DetalleEnTabla(Nullable<int> ventaId)
        {
            var ventaIdParameter = ventaId.HasValue ?
                new ObjectParameter("ventaId", ventaId) :
                new ObjectParameter("ventaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_DetalleEnTabla_Result6>("UDP_DetalleEnTabla", ventaIdParameter);
        }
    
        public virtual int UDP_EliminarVentaDetalle(Nullable<int> ventaDetalle_Id)
        {
            var ventaDetalle_IdParameter = ventaDetalle_Id.HasValue ?
                new ObjectParameter("ventaDetalle_Id", ventaDetalle_Id) :
                new ObjectParameter("ventaDetalle_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarVentaDetalle", ventaDetalle_IdParameter);
        }
    
        public virtual ObjectResult<UDP_DetalleEnTablaCompra_Result> UDP_DetalleEnTablaCompra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_DetalleEnTablaCompra_Result>("UDP_DetalleEnTablaCompra");
        }
    
        public virtual int UDP_InsertarCompraDetalles(string productoId, string compraDetallecantidad, string compraDetalleUsuarioCreacion)
        {
            var productoIdParameter = productoId != null ?
                new ObjectParameter("productoId", productoId) :
                new ObjectParameter("productoId", typeof(string));
    
            var compraDetallecantidadParameter = compraDetallecantidad != null ?
                new ObjectParameter("compraDetallecantidad", compraDetallecantidad) :
                new ObjectParameter("compraDetallecantidad", typeof(string));
    
            var compraDetalleUsuarioCreacionParameter = compraDetalleUsuarioCreacion != null ?
                new ObjectParameter("compraDetalleUsuarioCreacion", compraDetalleUsuarioCreacion) :
                new ObjectParameter("compraDetalleUsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarCompraDetalles", productoIdParameter, compraDetallecantidadParameter, compraDetalleUsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_DetalleEnTablaCompraxId_Result> UDP_DetalleEnTablaCompraxId(Nullable<int> compraId)
        {
            var compraIdParameter = compraId.HasValue ?
                new ObjectParameter("compraId", compraId) :
                new ObjectParameter("compraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_DetalleEnTablaCompraxId_Result>("UDP_DetalleEnTablaCompraxId", compraIdParameter);
        }
    
        public virtual int UDP_EliminarCompraDetalle(Nullable<int> compraDetalleId)
        {
            var compraDetalleIdParameter = compraDetalleId.HasValue ?
                new ObjectParameter("compraDetalleId", compraDetalleId) :
                new ObjectParameter("compraDetalleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarCompraDetalle", compraDetalleIdParameter);
        }
    
        public virtual ObjectResult<string> UDP_SelectUsuario(string usuarioUsuario)
        {
            var usuarioUsuarioParameter = usuarioUsuario != null ?
                new ObjectParameter("usuarioUsuario", usuarioUsuario) :
                new ObjectParameter("usuarioUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_SelectUsuario", usuarioUsuarioParameter);
        }
    
        public virtual int UDP_EditarDepartamentos(Nullable<int> idEdidcion, string departamento, Nullable<int> usuarioModificacion)
        {
            var idEdidcionParameter = idEdidcion.HasValue ?
                new ObjectParameter("IdEdidcion", idEdidcion) :
                new ObjectParameter("IdEdidcion", typeof(int));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarDepartamentos", idEdidcionParameter, departamentoParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_EliminarDepartamentos(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarDepartamentos", idEdicionParameter);
        }
    
        public virtual int UDP_EliminarMunicipios(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EliminarMunicipios", idEdicionParameter);
        }
    
        public virtual ObjectResult<UDP_IndexDepartamentos_Result> UDP_IndexDepartamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexDepartamentos_Result>("UDP_IndexDepartamentos");
        }
    
        public virtual ObjectResult<UDP_IndexMunicipios_Result> UDP_IndexMunicipios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_IndexMunicipios_Result>("UDP_IndexMunicipios");
        }
    
        public virtual int UDP_InsertaCategorias(string categoriaDescripcion, Nullable<int> categoriaUsuarioCreacion)
        {
            var categoriaDescripcionParameter = categoriaDescripcion != null ?
                new ObjectParameter("categoriaDescripcion", categoriaDescripcion) :
                new ObjectParameter("categoriaDescripcion", typeof(string));
    
            var categoriaUsuarioCreacionParameter = categoriaUsuarioCreacion.HasValue ?
                new ObjectParameter("categoriaUsuarioCreacion", categoriaUsuarioCreacion) :
                new ObjectParameter("categoriaUsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertaCategorias", categoriaDescripcionParameter, categoriaUsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_DDLEmpleados_Result> UDP_DDLEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_DDLEmpleados_Result>("UDP_DDLEmpleados");
        }
    
        public virtual ObjectResult<UDP_CargarUsuarios_Result> UDP_CargarUsuarios(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarUsuarios_Result>("UDP_CargarUsuarios", usuarioIdParameter);
        }
    
        public virtual int UDP_EdicionUsuario(Nullable<int> usuarioId, string usuarioUsuario)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            var usuarioUsuarioParameter = usuarioUsuario != null ?
                new ObjectParameter("usuarioUsuario", usuarioUsuario) :
                new ObjectParameter("usuarioUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EdicionUsuario", usuarioIdParameter, usuarioUsuarioParameter);
        }
    
        public virtual int UDP_InsertarUsuario(string usuario, string contrasenia, Nullable<int> empleado, Nullable<int> usuarioCreacion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseniaParameter = contrasenia != null ?
                new ObjectParameter("Contrasenia", contrasenia) :
                new ObjectParameter("Contrasenia", typeof(string));
    
            var empleadoParameter = empleado.HasValue ?
                new ObjectParameter("Empleado", empleado) :
                new ObjectParameter("Empleado", typeof(int));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarUsuario", usuarioParameter, contraseniaParameter, empleadoParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_SelectMunicipioxId_Result> UDP_SelectMunicipioxId(string municipioId)
        {
            var municipioIdParameter = municipioId != null ?
                new ObjectParameter("municipioId", municipioId) :
                new ObjectParameter("municipioId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_SelectMunicipioxId_Result>("UDP_SelectMunicipioxId", municipioIdParameter);
        }
    
        public virtual int UDP_EditarMunicipios(string idEdidcion, string municipio, Nullable<int> usuarioModificacion)
        {
            var idEdidcionParameter = idEdidcion != null ?
                new ObjectParameter("IdEdidcion", idEdidcion) :
                new ObjectParameter("IdEdidcion", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarMunicipios", idEdidcionParameter, municipioParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_InsertarMunicipios(string municipio, string departamento, Nullable<int> usuarioCreacion)
        {
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarMunicipios", municipioParameter, departamentoParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_LoginParaEmpleadoId(string usuario, string contrasenia)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseniaParameter = contrasenia != null ?
                new ObjectParameter("Contrasenia", contrasenia) :
                new ObjectParameter("Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_LoginParaEmpleadoId", usuarioParameter, contraseniaParameter);
        }
    
        public virtual ObjectResult<UDP_DDLMunicipios_Result> UDP_DDLMunicipios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_DDLMunicipios_Result>("UDP_DDLMunicipios");
        }
    
        public virtual ObjectResult<UDP_SelectCargoxId_Result1> UDP_SelectCargoxId(Nullable<int> cargoId)
        {
            var cargoIdParameter = cargoId.HasValue ?
                new ObjectParameter("cargoId", cargoId) :
                new ObjectParameter("cargoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_SelectCargoxId_Result1>("UDP_SelectCargoxId", cargoIdParameter);
        }
    
        public virtual int UDP_InsertarDepartamentos(string departamentoId, string departamento, Nullable<int> usuarioCreacion)
        {
            var departamentoIdParameter = departamentoId != null ?
                new ObjectParameter("DepartamentoId", departamentoId) :
                new ObjectParameter("DepartamentoId", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarDepartamentos", departamentoIdParameter, departamentoParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_MUNICIPIOxMunicipioId_Result> UDP_MUNICIPIOxMunicipioId(string municipioId)
        {
            var municipioIdParameter = municipioId != null ?
                new ObjectParameter("municipioId", municipioId) :
                new ObjectParameter("municipioId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_MUNICIPIOxMunicipioId_Result>("UDP_MUNICIPIOxMunicipioId", municipioIdParameter);
        }
    
        public virtual ObjectResult<UDP_CargarCategoria_Result> UDP_CargarCategoria(Nullable<int> categoriaId)
        {
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("categoriaId", categoriaId) :
                new ObjectParameter("categoriaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarCategoria_Result>("UDP_CargarCategoria", categoriaIdParameter);
        }
    
        public virtual int UDP_EditarCategorias(Nullable<int> idEdicion, string categoria, Nullable<int> usuarioModificacion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EditarCategorias", idEdicionParameter, categoriaParameter, usuarioModificacionParameter);
        }
    }
}
