//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCargos()
        {
            this.tbEmpleados = new HashSet<tbEmpleados>();
        }
    
        public int cargoId { get; set; }
        public string cargoNombre { get; set; }
        public System.DateTime cargoFechaCreacion { get; set; }
        public int cargoUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> cargoFechaModificacion { get; set; }
        public Nullable<int> cargoUsuarioModificacion { get; set; }
        public bool cargoEstado { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}
