//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompraDetalles
    {
        public int compraDetalleId { get; set; }
        public int compraId { get; set; }
        public int productoId { get; set; }
        public int compraDetallecatidad { get; set; }
        public decimal compraDetallePrecio { get; set; }
        public System.DateTime compraDetalleFechaCreacion { get; set; }
        public int compraDetalleUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> compraDetalleFechaModificacion { get; set; }
        public Nullable<int> compraDetalleUsuarioModificacion { get; set; }
        public bool compraDetalleEstado { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbCompras tbCompras { get; set; }
        public virtual tbProductos tbProductos { get; set; }
    }
}
