//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCompras()
        {
            this.tbCompraDetalles = new HashSet<tbCompraDetalles>();
        }
    
        public int compraId { get; set; }
        public int proveedorId { get; set; }
        public System.DateTime compraFecha { get; set; }
        public System.DateTime compraFechaCreacion { get; set; }
        public int compraUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> compraFechaModificacion { get; set; }
        public Nullable<int> compraUsuarioModificacion { get; set; }
        public bool compraEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompraDetalles> tbCompraDetalles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
    }
}
