//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadosCiviles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEstadosCiviles()
        {
            this.tbEmpleados = new HashSet<tbEmpleados>();
        }
    
        public string estadoCivilId { get; set; }
        public string estadoCivilNombre { get; set; }
        public System.DateTime estadoCivilFechaCreacion { get; set; }
        public int estadoCivilUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> estadoCivilFechaModificacion { get; set; }
        public Nullable<int> estadoCivilUsuarioModificacion { get; set; }
        public bool estadoCivilEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
