//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMetodoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMetodoPago()
        {
            this.tbventa = new HashSet<tbventa>();
        }
    
        public string metodopagoId { get; set; }
        public string metodopagoDescripcion { get; set; }
        public System.DateTime metodopagoFechaCreacion { get; set; }
        public int metodopagoUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> metodopagoFechaModificacion { get; set; }
        public Nullable<int> metodopagoUsuarioModificacion { get; set; }
        public bool metodopagoEstado { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbventa> tbventa { get; set; }
    }
}
