//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProductos()
        {
            this.tbCompraDetalles = new HashSet<tbCompraDetalles>();
            this.tbventaDetalles = new HashSet<tbventaDetalles>();
        }
    
        public int productoId { get; set; }
        public string productoNombre { get; set; }
        public decimal productoPrecio { get; set; }
        public int categoriaId { get; set; }
        public int proveedorid { get; set; }
        public int productoStock { get; set; }
        public System.DateTime productoFechaCreacion { get; set; }
        public int productoUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> productoFechaModificacion { get; set; }
        public Nullable<int> productoUsuarioModificacion { get; set; }
        public bool productoEstado { get; set; }
    
        public virtual tbCategoria tbCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompraDetalles> tbCompraDetalles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbventaDetalles> tbventaDetalles { get; set; }
    }
}
