//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Ventas.Models
{
    using System;
    
    public partial class UDP_DetalleEnTabla_Result4
    {
        public string productoNombre { get; set; }
        public decimal ventaDetalle_Precio { get; set; }
        public int ventaDetalle_catidad { get; set; }
    }
}
